import { THeroTrend } from "./../src/types/index";
export const HERO_LIST = [
  "nature's prophet",
  "outworld devourer",
  "windranger",
  "zeus",
  "shadow fiend",
  "vengeful spirit",
  "timbersaw",
  "naix",
  "anti mage",
  "axe",
  "bane",
  "bloodseeker",
  "centaur warrunner",
  "crystal maiden",
  "drow ranger",
  "earthshaker",
  "juggernaut",
  "mirana",
  "morphling",
  "phantom lancer",
  "puck",
  "pudge",
  "razor",
  "sand king",
  "storm spirit",
  "sven",
  "tiny",
  "vengefulspirit",
  "kunkka",
  "lina",
  "lion",
  "shadow shaman",
  "slardar",
  "tidehunter",
  "witch doctor",
  "lich",
  "riki",
  "enigma",
  "tinker",
  "sniper",
  "necrophos",
  "warlock",
  "beastmaster",
  "queen of pain",
  "venomancer",
  "faceless void",
  "skeleton king",
  "death prophet",
  "phantom assassin",
  "pugna",
  "templar assassin",
  "viper",
  "luna",
  "dragon knight",
  "dazzle",
  "leshrac",
  "life stealer",
  "dark seer",
  "clinkz",
  "omniknight",
  "enchantress",
  "huskar",
  "night stalker",
  "broodmother",
  "bounty hunter",
  "weaver",
  "jakiro",
  "batrider",
  "chen",
  "spectre",
  "ancient apparition",
  "doom",
  "ursa",
  "spirit breaker",
  "gyrocopter",
  "alchemist",
  "invoker",
  "silencer",
  "obsidian destroyer",
  "lycan",
  "brewmaster",
  "shadow demon",
  "lone druid",
  "chaos knight",
  "meepo",
  "treant protector",
  "ogre magi",
  "undying",
  "rubick",
  "disruptor",
  "nyx assassin",
  "naga siren",
  "keeper of the light",
  "wisp",
  "visage",
  "slark",
  "medusa",
  "troll warlord",
  "centaur",
  "magnataur",
  "shredder",
  "bristleback",
  "tusk",
  "skywrath mage",
  "abaddon",
  "elder titan",
  "legion commander",
  "techies",
  "ember spirit",
  "earth spirit",
  "abyssal underlord",
  "terrorblade",
  "phoenix",
  "oracle",
  "winter wyvern",
  "arc warden",
  "monkey king",
  "dark willow",
  "pangolier",
  "grimstroke",
  "hoodwink",
  "void spirit",
  "snapfire",
  "mars",
  "dawnbreaker",
  "marci",
  "primal beast",
  "io",
  "underlord",
  "clockwerk",
  "omnni",
  "magnus",
  "lifestealer",
  "wraith king",
];

export const DEFAULT_HERO_TREND: THeroTrend[] = [
  {
    id: 1,
    name: "npc_dota_hero_antimage",
    localized_name: "Anti-Mage",
    icon: "/apps/dota2/images/dota_react/heroes/icons/antimage.png?",
    hero_id: 1,
    pro_ban: 406,
    pro_pick: 74,
    pro_win: 38,
    pro_wr: 13,
    "1_pick": 41185,
    "1_win": 22958,
    "1_wr": 55.74,
    "2_pick": 60684,
    "2_win": 32906,
    "2_wr": 54.23,
    "3_pick": 57065,
    "3_win": 30593,
    "3_wr": 53.61,
    "4_pick": 40662,
    "4_win": 21238,
    "4_wr": 52.23,
    "5_pick": 21628,
    "5_win": 11149,
    "5_wr": 51.55,
    "6_pick": 9530,
    "6_win": 4923,
    "6_wr": 51.66,
    "7_pick": 4301,
    "7_win": 2140,
    "7_wr": 49.76,
    "8_pick": 1135,
    "8_win": 539,
    "8_wr": 47.49,
    turbo_picks: 250102,
    turbo_wins: 126983,
  },
];

export const COLUMN_HEADERS = [
  "id",
  "name",
  "Name",
  "icon",
  "hero_id",
  "pro ban",
  "pro_pick",
  "pro win",
  "pro_wr (%)",
  "1_pick",
  "1_win",
  "1_wr (%)",
  "2_pick",
  "2_win",
  "2_wr (%)",
  "3_pick",
  "3_win",
  "3_wr (%)",
  "4_pick",
  "4_win",
  "4_wr (%)",
  "5_pick",
  "5_win",
  "5_wr (%)",
  "6_pick",
  "6_win",
  "6_wr (%)",
  "7_pick",
  "7_win",
  "7_wr (%)",
  "8_pick",
  "8_win (%)",
  "8_wr (%)",
  "turbo_picks",
  "turbo_wins",
];[]