import { THeroTrend } from "./../src/types/index";
export const HERO_LIST = [
  "nature's prophet",
  "outworld devourer",
  "windranger",
  "zeus",
  "shadow fiend",
  "vengeful spirit",
  "timbersaw",
  "naix",
  "anti mage",
  "axe",
  "bane",
  "bloodseeker",
  "centaur warrunner",
  "crystal maiden",
  "drow ranger",
  "earthshaker",
  "juggernaut",
  "mirana",
  "morphling",
  "phantom lancer",
  "puck",
  "pudge",
  "razor",
  "sand king",
  "storm spirit",
  "sven",
  "tiny",
  "vengefulspirit",
  "kunkka",
  "lina",
  "lion",
  "shadow shaman",
  "slardar",
  "tidehunter",
  "witch doctor",
  "lich",
  "riki",
  "enigma",
  "tinker",
  "sniper",
  "necrophos",
  "warlock",
  "beastmaster",
  "queen of pain",
  "venomancer",
  "faceless void",
  "skeleton king",
  "death prophet",
  "phantom assassin",
  "pugna",
  "templar assassin",
  "viper",
  "luna",
  "dragon knight",
  "dazzle",
  "leshrac",
  "life stealer",
  "dark seer",
  "clinkz",
  "omniknight",
  "enchantress",
  "huskar",
  "night stalker",
  "broodmother",
  "bounty hunter",
  "weaver",
  "jakiro",
  "batrider",
  "chen",
  "spectre",
  "ancient apparition",
  "doom",
  "ursa",
  "spirit breaker",
  "gyrocopter",
  "alchemist",
  "invoker",
  "silencer",
  "obsidian destroyer",
  "lycan",
  "brewmaster",
  "shadow demon",
  "lone druid",
  "chaos knight",
  "meepo",
  "treant protector",
  "ogre magi",
  "undying",
  "rubick",
  "disruptor",
  "nyx assassin",
  "naga siren",
  "keeper of the light",
  "wisp",
  "visage",
  "slark",
  "medusa",
  "troll warlord",
  "centaur",
  "magnataur",
  "shredder",
  "bristleback",
  "tusk",
  "skywrath mage",
  "abaddon",
  "elder titan",
  "legion commander",
  "techies",
  "ember spirit",
  "earth spirit",
  "abyssal underlord",
  "terrorblade",
  "phoenix",
  "oracle",
  "winter wyvern",
  "arc warden",
  "monkey king",
  "dark willow",
  "pangolier",
  "grimstroke",
  "hoodwink",
  "void spirit",
  "snapfire",
  "mars",
  "dawnbreaker",
  "marci",
  "primal beast",
  "io",
  "underlord",
  "clockwerk",
  "omnni",
  "magnus",
  "lifestealer",
  "wraith king",
];

export const DEFAULT_HERO_TREND: THeroTrend[] = [
  {
    id: 1,
    name: "npc_dota_hero_antimage",
    localized_name: "Anti-Mage",
    icon: "/apps/dota2/images/dota_react/heroes/icons/antimage.png?",
    hero_id: 1,
    pro_ban: 406,
    pro_pick: 74,
    pro_win: 38,
    pro_wr: 13,
    "1_pick": 41185,
    "1_win": 22958,
    "1_wr": 55.74,
    "2_pick": 60684,
    "2_win": 32906,
    "2_wr": 54.23,
    "3_pick": 57065,
    "3_win": 30593,
    "3_wr": 53.61,
    "4_pick": 40662,
    "4_win": 21238,
    "4_wr": 52.23,
    "5_pick": 21628,
    "5_win": 11149,
    "5_wr": 51.55,
    "6_pick": 9530,
    "6_win": 4923,
    "6_wr": 51.66,
    "7_pick": 4301,
    "7_win": 2140,
    "7_wr": 49.76,
    "8_pick": 1135,
    "8_win": 539,
    "8_wr": 47.49,
    turbo_picks: 250102,
    turbo_wins: 126983,
  },
];

export const COLUMN_HEADERS = [
  "id",
  "name",
  "Name",
  "icon",
  "hero_id",
  "pro ban",
  "pro_pick",
  "pro win",
  "pro_wr (%)",
  "1_pick",
  "1_win",
  "1_wr (%)",
  "2_pick",
  "2_win",
  "2_wr (%)",
  "3_pick",
  "3_win",
  "3_wr (%)",
  "4_pick",
  "4_win",
  "4_wr (%)",
  "5_pick",
  "5_win",
  "5_wr (%)",
  "6_pick",
  "6_win",
  "6_wr (%)",
  "7_pick",
  "7_win",
  "7_wr (%)",
  "8_pick",
  "8_win (%)",
  "8_wr (%)",
  "turbo_picks",
  "turbo_wins",
];

export const HERO_ICONS = [
  "/apps/dota2/images/dota_react/heroes/icons/antimage.png?",
  "/apps/dota2/images/dota_react/heroes/icons/axe.png?",
  "/apps/dota2/images/dota_react/heroes/icons/bane.png?",
  "/apps/dota2/images/dota_react/heroes/icons/bloodseeker.png?",
  "/apps/dota2/images/dota_react/heroes/icons/crystal_maiden.png?",
  "/apps/dota2/images/dota_react/heroes/icons/drow_ranger.png?",
  "/apps/dota2/images/dota_react/heroes/icons/earthshaker.png?",
  "/apps/dota2/images/dota_react/heroes/icons/juggernaut.png?",
  "/apps/dota2/images/dota_react/heroes/icons/mirana.png?",
  "/apps/dota2/images/dota_react/heroes/icons/morphling.png?",
  "/apps/dota2/images/dota_react/heroes/icons/nevermore.png?",
  "/apps/dota2/images/dota_react/heroes/icons/phantom_lancer.png?",
  "/apps/dota2/images/dota_react/heroes/icons/puck.png?",
  "/apps/dota2/images/dota_react/heroes/icons/pudge.png?",
  "/apps/dota2/images/dota_react/heroes/icons/razor.png?",
  "/apps/dota2/images/dota_react/heroes/icons/sand_king.png?",
  "/apps/dota2/images/dota_react/heroes/icons/storm_spirit.png?",
  "/apps/dota2/images/dota_react/heroes/icons/sven.png?",
  "/apps/dota2/images/dota_react/heroes/icons/tiny.png?",
  "/apps/dota2/images/dota_react/heroes/icons/vengefulspirit.png?",
  "/apps/dota2/images/dota_react/heroes/icons/windrunner.png?",
  "/apps/dota2/images/dota_react/heroes/icons/zuus.png?",
  "/apps/dota2/images/dota_react/heroes/icons/kunkka.png?",
  "/apps/dota2/images/dota_react/heroes/icons/lina.png?",
  "/apps/dota2/images/dota_react/heroes/icons/lion.png?",
  "/apps/dota2/images/dota_react/heroes/icons/shadow_shaman.png?",
  "/apps/dota2/images/dota_react/heroes/icons/slardar.png?",
  "/apps/dota2/images/dota_react/heroes/icons/tidehunter.png?",
  "/apps/dota2/images/dota_react/heroes/icons/witch_doctor.png?",
  "/apps/dota2/images/dota_react/heroes/icons/lich.png?",
  "/apps/dota2/images/dota_react/heroes/icons/riki.png?",
  "/apps/dota2/images/dota_react/heroes/icons/enigma.png?",
  "/apps/dota2/images/dota_react/heroes/icons/tinker.png?",
  "/apps/dota2/images/dota_react/heroes/icons/sniper.png?",
  "/apps/dota2/images/dota_react/heroes/icons/necrolyte.png?",
  "/apps/dota2/images/dota_react/heroes/icons/warlock.png?",
  "/apps/dota2/images/dota_react/heroes/icons/beastmaster.png?",
  "/apps/dota2/images/dota_react/heroes/icons/queenofpain.png?",
  "/apps/dota2/images/dota_react/heroes/icons/venomancer.png?",
  "/apps/dota2/images/dota_react/heroes/icons/faceless_void.png?",
  "/apps/dota2/images/dota_react/heroes/icons/skeleton_king.png?",
  "/apps/dota2/images/dota_react/heroes/icons/death_prophet.png?",
  "/apps/dota2/images/dota_react/heroes/icons/phantom_assassin.png?",
  "/apps/dota2/images/dota_react/heroes/icons/pugna.png?",
  "/apps/dota2/images/dota_react/heroes/icons/templar_assassin.png?",
  "/apps/dota2/images/dota_react/heroes/icons/viper.png?",
  "/apps/dota2/images/dota_react/heroes/icons/luna.png?",
  "/apps/dota2/images/dota_react/heroes/icons/dragon_knight.png?",
  "/apps/dota2/images/dota_react/heroes/icons/dazzle.png?",
  "/apps/dota2/images/dota_react/heroes/icons/rattletrap.pg?",
  "/apps/dota2/images/dota_react/heroes/icons/leshrac.png?",
  "/apps/dota2/images/dota_react/heroes/icons/furion.png?",
  "/apps/dota2/images/dota_react/heroes/icons/life_stealer.png?",
  "/apps/dota2/images/dota_react/heroes/icons/dark_seer.png?",
  "/apps/dota2/images/dota_react/heroes/icons/clinkz.png?",
  "/apps/dota2/images/dota_react/heroes/icons/omniknight.png?",
  "/apps/dota2/images/dota_react/heroes/icons/enchantress.png?",
  "/apps/dota2/images/dota_react/heroes/icons/huskar.png?",
  "/apps/dota2/images/dota_react/heroes/icons/night_stalker.png?",
  "/apps/dota2/images/dota_react/heroes/icons/broodmother.png?",
  "/apps/dota2/images/dota_react/heroes/icons/bounty_hunter.png?",
  "/apps/dota2/images/dota_react/heroes/icons/weaver.png?",
  "/apps/dota2/images/dota_react/heroes/icons/jakiro.png?",
  "/apps/dota2/images/dota_react/heroes/icons/batrider.png?",
  "/apps/dota2/images/dota_react/heroes/icons/chen.png?",
  "/apps/dota2/images/dota_react/heroes/icons/spectre.png?",
  "/apps/dota2/images/dota_react/heroes/icons/ancient_apparition.png?",
  "/apps/dota2/images/dota_react/heroes/icons/doom_bringer.png?",
  "/apps/dota2/images/dota_react/heroes/icons/ursa.png?",
  "/apps/dota2/images/dota_react/heroes/icons/spirit_breaker.png?",
  "/apps/dota2/images/dota_react/heroes/icons/gyrocopter.png?",
  "/apps/dota2/images/dota_react/heroes/icons/alchemist.png?",
  "/apps/dota2/images/dota_react/heroes/icons/invoker.png?",
  "/apps/dota2/images/dota_react/heroes/icons/silencer.png?",
  "/apps/dota2/images/dota_react/heroes/icons/obsidian_destroyer.png?",
  "/apps/dota2/images/dota_react/heroes/icons/lycan.png?",
  "/apps/dota2/images/dota_react/heroes/icons/brewmaster.png?",
  "/apps/dota2/images/dota_react/heroes/icons/shadow_demon.png?",
  "/apps/dota2/images/dota_react/heroes/icons/lone_druid.png?",
  "/apps/dota2/images/dota_react/heroes/icons/chaos_knight.png?",
  "/apps/dota2/images/dota_react/heroes/icons/meepo.png?",
  "/apps/dota2/images/dota_react/heroes/icons/treant.png?",
  "/apps/dota2/images/dota_react/heroes/icons/ogre_magi.png?",
  "/apps/dota2/images/dota_react/heroes/icons/undying.png?",
  "/apps/dota2/images/dota_react/heroes/icons/rubick.png?",
  "/apps/dota2/images/dota_react/heroes/icons/disruptor.png?",
  "/apps/dota2/images/dota_react/heroes/icons/nyx_assassin.png?",
  "/apps/dota2/images/dota_react/heroes/icons/naga_siren.png?",
  "/apps/dota2/images/dota_react/heroes/icons/keeper_of_the_light.png?",
  "/apps/dota2/images/dota_react/heroes/icons/wisp.png?",
  "/apps/dota2/images/dota_react/heroes/icons/visage.png?",
  "/apps/dota2/images/dota_react/heroes/icons/slark.png?",
  "/apps/dota2/images/dota_react/heroes/icons/medusa.png?",
  "/apps/dota2/images/dota_react/heroes/icons/troll_warlord.png?",
  "/apps/dota2/images/dota_react/heroes/icons/centaur.png?",
  "/apps/dota2/images/dota_react/heroes/icons/magnataur.png?",
  "/apps/dota2/images/dota_react/heroes/icons/shredder.png?",
  "/apps/dota2/images/dota_react/heroes/icons/bristleback.png?",
  "/apps/dota2/images/dota_react/heroes/icons/tusk.png?",
  "/apps/dota2/images/dota_react/heroes/icons/skywrath_mage.png?",
  "/apps/dota2/images/dota_react/heroes/icons/abaddon.png?",
  "/apps/dota2/images/dota_react/heroes/icons/elder_titan.png?",
  "/apps/dota2/images/dota_react/heroes/icons/legion_commander.png?",
  "/apps/dota2/images/dota_react/heroes/icons/techies.png?",
  "/apps/dota2/images/dota_react/heroes/icons/ember_spirit.png?",
  "/apps/dota2/images/dota_react/heroes/icons/earth_spirit.png?",
  "/apps/dota2/images/dota_react/heroes/icons/abyssal_underlord.png?",
  "/apps/dota2/images/dota_react/heroes/icons/terrorblade.png?",
  "/apps/dota2/images/dota_react/heroes/icons/phoenix.png?",
  "/apps/dota2/images/dota_react/heroes/icons/oracle.png?",
  "/apps/dota2/images/dota_react/heroes/icons/winter_wyvern.png?",
  "/apps/dota2/images/dota_react/heroes/icons/arc_warden.png?",
  "/apps/dota2/images/dota_react/heroes/icons/monkey_king.png?",
  "/apps/dota2/images/dota_react/heroes/icons/dark_willow.png?",
  "/apps/dota2/images/dota_react/heroes/icons/pangolier.png?",
  "/apps/dota2/images/dota_react/heroes/icons/grimstroke.png?",
  "/apps/dota2/images/dota_react/heroes/icons/hoodwink.png?",
  "/apps/dota2/images/dota_react/heroes/icons/void_spirit.png?",
  "/apps/dota2/images/dota_react/heroes/icons/snapfire.png?",
  "/apps/dota2/images/dota_react/heroes/icons/mars.png?",
  "/apps/dota2/images/dota_react/heroes/icons/dawnbreaker.png?",
  "/apps/dota2/images/dota_react/heroes/icons/marci.png?",
  "/apps/dota2/images/dota_react/heroes/icons/primal_beast.png",
];
