import { THeroTrend } from "./../src/types/index";
export const HERO_LIST = [
  "nature's prophet",
  "outworld devourer",
  "windranger",
  "zeus",
  "shadow fiend",
  "vengeful spirit",
  "timbersaw",
  "naix",
  "anti mage",
  "axe",
  "bane",
  "bloodseeker",
  "centaur warrunner",
  "crystal maiden",
  "drow ranger",
  "earthshaker",
  "juggernaut",
  "mirana",
  "morphling",
  "phantom lancer",
  "puck",
  "pudge",
  "razor",
  "sand king",
  "storm spirit",
  "sven",
  "tiny",
  "vengefulspirit",
  "kunkka",
  "lina",
  "lion",
  "shadow shaman",
  "slardar",
  "tidehunter",
  "witch doctor",
  "lich",
  "riki",
  "enigma",
  "tinker",
  "sniper",
  "necrophos",
  "warlock",
  "beastmaster",
  "queen of pain",
  "venomancer",
  "faceless void",
  "skeleton king",
  "death prophet",
  "phantom assassin",
  "pugna",
  "templar assassin",
  "viper",
  "luna",
  "dragon knight",
  "dazzle",
  "leshrac",
  "life stealer",
  "dark seer",
  "clinkz",
  "omniknight",
  "enchantress",
  "huskar",
  "night stalker",
  "broodmother",
  "bounty hunter",
  "weaver",
  "jakiro",
  "batrider",
  "chen",
  "spectre",
  "ancient apparition",
  "doom",
  "ursa",
  "spirit breaker",
  "gyrocopter",
  "alchemist",
  "invoker",
  "silencer",
  "obsidian destroyer",
  "lycan",
  "brewmaster",
  "shadow demon",
  "lone druid",
  "chaos knight",
  "meepo",
  "treant protector",
  "ogre magi",
  "undying",
  "rubick",
  "disruptor",
  "nyx assassin",
  "naga siren",
  "keeper of the light",
  "wisp",
  "visage",
  "slark",
  "medusa",
  "troll warlord",
  "centaur",
  "magnataur",
  "shredder",
  "bristleback",
  "tusk",
  "skywrath mage",
  "abaddon",
  "elder titan",
  "legion commander",
  "techies",
  "ember spirit",
  "earth spirit",
  "abyssal underlord",
  "terrorblade",
  "phoenix",
  "oracle",
  "winter wyvern",
  "arc warden",
  "monkey king",
  "dark willow",
  "pangolier",
  "grimstroke",
  "hoodwink",
  "void spirit",
  "snapfire",
  "mars",
  "dawnbreaker",
  "marci",
  "primal beast",
  "io",
  "underlord",
  "clockwerk",
  "omnni",
  "magnus",
  "lifestealer",
  "wraith king",
];

export const DEFAULT_HERO_TREND: THeroTrend[] = [
  {
    id: 0,
    name: " ",
    localized_name: "Loading...",
    icon: " ",
    hero_id: 0,
    pro_ban: 0,
    pro_pick: 0,
    pro_win: 0,
    pro_wr: 0,
    "1_pick": 0,
    "1_win": 0,
    "1_wr": 0,
    "2_pick": 0,
    "2_win": 0,
    "2_wr": 0,
    "3_pick": 0,
    "3_win": 0,
    "3_wr": 0,
    "4_pick": 0,
    "4_win": 0,
    "4_wr": 0,
    "5_pick": 0,
    "5_win": 0,
    "5_wr": 0,
    "6_pick": 0,
    "6_win": 0,
    "6_wr": 0,
    "7_pick": 0,
    "7_win": 0,
    "7_wr": 0,
    "8_pick": 0,
    "8_win": 0,
    "8_wr": 0,
    turbo_picks: 0,
    turbo_wins: 0,
  },
];

export const COLUMN_HEADERS = [
  "id",
  "name",
  "Name",
  "icon",
  "hero_id",
  "pro ban",
  "pro_pick",
  "pro win",
  "pro_wr (%)",
  "1_pick",
  "1_win",
  "1_wr (%)",
  "2_pick",
  "2_win",
  "2_wr (%)",
  "3_pick",
  "3_win",
  "3_wr (%)",
  "4_pick",
  "4_win",
  "4_wr (%)",
  "5_pick",
  "5_win",
  "5_wr (%)",
  "6_pick",
  "6_win",
  "6_wr (%)",
  "7_pick",
  "7_win",
  "7_wr (%)",
  "8_pick",
  "8_win (%)",
  "8_wr (%)",
  "turbo_picks",
  "turbo_wins",
];

export const HERO_ICONS = [
  "/apps/dota2/images/dota_react/heroes/icons/antimage.png?",
  "/apps/dota2/images/dota_react/heroes/icons/axe.png?",
  "/apps/dota2/images/dota_react/heroes/icons/bane.png?",
  "/apps/dota2/images/dota_react/heroes/icons/bloodseeker.png?",
  "/apps/dota2/images/dota_react/heroes/icons/crystal_maiden.png?",
  "/apps/dota2/images/dota_react/heroes/icons/drow_ranger.png?",
  "/apps/dota2/images/dota_react/heroes/icons/earthshaker.png?",
  "/apps/dota2/images/dota_react/heroes/icons/juggernaut.png?",
  "/apps/dota2/images/dota_react/heroes/icons/mirana.png?",
  "/apps/dota2/images/dota_react/heroes/icons/morphling.png?",
  "/apps/dota2/images/dota_react/heroes/icons/nevermore.png?",
  "/apps/dota2/images/dota_react/heroes/icons/phantom_lancer.png?",
  "/apps/dota2/images/dota_react/heroes/icons/puck.png?",
  "/apps/dota2/images/dota_react/heroes/icons/pudge.png?",
  "/apps/dota2/images/dota_react/heroes/icons/razor.png?",
  "/apps/dota2/images/dota_react/heroes/icons/sand_king.png?",
  "/apps/dota2/images/dota_react/heroes/icons/storm_spirit.png?",
  "/apps/dota2/images/dota_react/heroes/icons/sven.png?",
  "/apps/dota2/images/dota_react/heroes/icons/tiny.png?",
  "/apps/dota2/images/dota_react/heroes/icons/vengefulspirit.png?",
  "/apps/dota2/images/dota_react/heroes/icons/windrunner.png?",
  "/apps/dota2/images/dota_react/heroes/icons/zuus.png?",
  "/apps/dota2/images/dota_react/heroes/icons/kunkka.png?",
  "/apps/dota2/images/dota_react/heroes/icons/lina.png?",
  "/apps/dota2/images/dota_react/heroes/icons/lion.png?",
  "/apps/dota2/images/dota_react/heroes/icons/shadow_shaman.png?",
  "/apps/dota2/images/dota_react/heroes/icons/slardar.png?",
  "/apps/dota2/images/dota_react/heroes/icons/tidehunter.png?",
  "/apps/dota2/images/dota_react/heroes/icons/witch_doctor.png?",
  "/apps/dota2/images/dota_react/heroes/icons/lich.png?",
  "/apps/dota2/images/dota_react/heroes/icons/riki.png?",
  "/apps/dota2/images/dota_react/heroes/icons/enigma.png?",
  "/apps/dota2/images/dota_react/heroes/icons/tinker.png?",
  "/apps/dota2/images/dota_react/heroes/icons/sniper.png?",
  "/apps/dota2/images/dota_react/heroes/icons/necrolyte.png?",
  "/apps/dota2/images/dota_react/heroes/icons/warlock.png?",
  "/apps/dota2/images/dota_react/heroes/icons/beastmaster.png?",
  "/apps/dota2/images/dota_react/heroes/icons/queenofpain.png?",
  "/apps/dota2/images/dota_react/heroes/icons/venomancer.png?",
  "/apps/dota2/images/dota_react/heroes/icons/faceless_void.png?",
  "/apps/dota2/images/dota_react/heroes/icons/skeleton_king.png?",
  "/apps/dota2/images/dota_react/heroes/icons/death_prophet.png?",
  "/apps/dota2/images/dota_react/heroes/icons/phantom_assassin.png?",
  "/apps/dota2/images/dota_react/heroes/icons/pugna.png?",
  "/apps/dota2/images/dota_react/heroes/icons/templar_assassin.png?",
  "/apps/dota2/images/dota_react/heroes/icons/viper.png?",
  "/apps/dota2/images/dota_react/heroes/icons/luna.png?",
  "/apps/dota2/images/dota_react/heroes/icons/dragon_knight.png?",
  "/apps/dota2/images/dota_react/heroes/icons/dazzle.png?",
  "/apps/dota2/images/dota_react/heroes/icons/rattletrap.png?",
  "/apps/dota2/images/dota_react/heroes/icons/leshrac.png?",
  "/apps/dota2/images/dota_react/heroes/icons/furion.png?",
  "/apps/dota2/images/dota_react/heroes/icons/life_stealer.png?",
  "/apps/dota2/images/dota_react/heroes/icons/dark_seer.png?",
  "/apps/dota2/images/dota_react/heroes/icons/clinkz.png?",
  "/apps/dota2/images/dota_react/heroes/icons/omniknight.png?",
  "/apps/dota2/images/dota_react/heroes/icons/enchantress.png?",
  "/apps/dota2/images/dota_react/heroes/icons/huskar.png?",
  "/apps/dota2/images/dota_react/heroes/icons/night_stalker.png?",
  "/apps/dota2/images/dota_react/heroes/icons/broodmother.png?",
  "/apps/dota2/images/dota_react/heroes/icons/bounty_hunter.png?",
  "/apps/dota2/images/dota_react/heroes/icons/weaver.png?",
  "/apps/dota2/images/dota_react/heroes/icons/jakiro.png?",
  "/apps/dota2/images/dota_react/heroes/icons/batrider.png?",
  "/apps/dota2/images/dota_react/heroes/icons/chen.png?",
  "/apps/dota2/images/dota_react/heroes/icons/spectre.png?",
  "/apps/dota2/images/dota_react/heroes/icons/ancient_apparition.png?",
  "/apps/dota2/images/dota_react/heroes/icons/doom_bringer.png?",
  "/apps/dota2/images/dota_react/heroes/icons/ursa.png?",
  "/apps/dota2/images/dota_react/heroes/icons/spirit_breaker.png?",
  "/apps/dota2/images/dota_react/heroes/icons/gyrocopter.png?",
  "/apps/dota2/images/dota_react/heroes/icons/alchemist.png?",
  "/apps/dota2/images/dota_react/heroes/icons/invoker.png?",
  "/apps/dota2/images/dota_react/heroes/icons/silencer.png?",
  "/apps/dota2/images/dota_react/heroes/icons/obsidian_destroyer.png?",
  "/apps/dota2/images/dota_react/heroes/icons/lycan.png?",
  "/apps/dota2/images/dota_react/heroes/icons/brewmaster.png?",
  "/apps/dota2/images/dota_react/heroes/icons/shadow_demon.png?",
  "/apps/dota2/images/dota_react/heroes/icons/lone_druid.png?",
  "/apps/dota2/images/dota_react/heroes/icons/chaos_knight.png?",
  "/apps/dota2/images/dota_react/heroes/icons/meepo.png?",
  "/apps/dota2/images/dota_react/heroes/icons/treant.png?",
  "/apps/dota2/images/dota_react/heroes/icons/ogre_magi.png?",
  "/apps/dota2/images/dota_react/heroes/icons/undying.png?",
  "/apps/dota2/images/dota_react/heroes/icons/rubick.png?",
  "/apps/dota2/images/dota_react/heroes/icons/disruptor.png?",
  "/apps/dota2/images/dota_react/heroes/icons/nyx_assassin.png?",
  "/apps/dota2/images/dota_react/heroes/icons/naga_siren.png?",
  "/apps/dota2/images/dota_react/heroes/icons/keeper_of_the_light.png?",
  "/apps/dota2/images/dota_react/heroes/icons/wisp.png?",
  "/apps/dota2/images/dota_react/heroes/icons/visage.png?",
  "/apps/dota2/images/dota_react/heroes/icons/slark.png?",
  "/apps/dota2/images/dota_react/heroes/icons/medusa.png?",
  "/apps/dota2/images/dota_react/heroes/icons/troll_warlord.png?",
  "/apps/dota2/images/dota_react/heroes/icons/centaur.png?",
  "/apps/dota2/images/dota_react/heroes/icons/magnataur.png?",
  "/apps/dota2/images/dota_react/heroes/icons/shredder.png?",
  "/apps/dota2/images/dota_react/heroes/icons/bristleback.png?",
  "/apps/dota2/images/dota_react/heroes/icons/tusk.png?",
  "/apps/dota2/images/dota_react/heroes/icons/skywrath_mage.png?",
  "/apps/dota2/images/dota_react/heroes/icons/abaddon.png?",
  "/apps/dota2/images/dota_react/heroes/icons/elder_titan.png?",
  "/apps/dota2/images/dota_react/heroes/icons/legion_commander.png?",
  "/apps/dota2/images/dota_react/heroes/icons/techies.png?",
  "/apps/dota2/images/dota_react/heroes/icons/ember_spirit.png?",
  "/apps/dota2/images/dota_react/heroes/icons/earth_spirit.png?",
  "/apps/dota2/images/dota_react/heroes/icons/abyssal_underlord.png?",
  "/apps/dota2/images/dota_react/heroes/icons/terrorblade.png?",
  "/apps/dota2/images/dota_react/heroes/icons/phoenix.png?",
  "/apps/dota2/images/dota_react/heroes/icons/oracle.png?",
  "/apps/dota2/images/dota_react/heroes/icons/winter_wyvern.png?",
  "/apps/dota2/images/dota_react/heroes/icons/arc_warden.png?",
  "/apps/dota2/images/dota_react/heroes/icons/monkey_king.png?",
  "/apps/dota2/images/dota_react/heroes/icons/dark_willow.png?",
  "/apps/dota2/images/dota_react/heroes/icons/pangolier.png?",
  "/apps/dota2/images/dota_react/heroes/icons/grimstroke.png?",
  "/apps/dota2/images/dota_react/heroes/icons/hoodwink.png?",
  "/apps/dota2/images/dota_react/heroes/icons/void_spirit.png?",
  "/apps/dota2/images/dota_react/heroes/icons/snapfire.png?",
  "/apps/dota2/images/dota_react/heroes/icons/mars.png?",
  "/apps/dota2/images/dota_react/heroes/icons/dawnbreaker.png?",
  "/apps/dota2/images/dota_react/heroes/icons/marci.png?",
  "/apps/dota2/images/dota_react/heroes/icons/primal_beast.png?",
];

export const REGIONS = {
  "1": "US WEST",
  "2": "US EAST",
  "3": "EUROPE",
  "5": "SINGAPORE",
  "6": "DUBAI",
  "7": "AUSTRALIA",
  "8": "STOCKHOLM",
  "9": "AUSTRIA",
  "10": "BRAZIL",
  "11": "SOUTHAFRICA",
  "12": "PW TELECOM SHANGHAI",
  "13": "PW UNICOM",
  "14": "CHILE",
  "15": "PERU",
  "16": "INDIA",
  "17": "PW TELECOM GUANGDONG",
  "18": "PW TELECOM ZHEJIANG",
  "19": "JAPAN",
  "20": "PW TELECOM WUHAN",
  "25": "PW UNICOM TIANJIN",
  "37": "TAIWAN",
  "38": "ARGENTINA",
};

export const CLUSTERS = {
  "111": 1,
  "112": 1,
  "113": 1,
  "114": 1,
  "117": 1,
  "118": 1,
  "121": 2,
  "122": 2,
  "123": 2,
  "124": 2,
  "131": 3,
  "132": 3,
  "133": 3,
  "134": 3,
  "135": 3,
  "136": 3,
  "137": 3,
  "138": 3,
  "141": 19,
  "142": 19,
  "143": 19,
  "144": 19,
  "145": 19,
  "151": 5,
  "152": 5,
  "153": 5,
  "154": 5,
  "155": 5,
  "156": 5,
  "161": 6,
  "162": 6,
  "163": 6,
  "171": 7,
  "172": 7,
  "181": 8,
  "182": 8,
  "183": 8,
  "184": 8,
  "185": 8,
  "186": 8,
  "187": 8,
  "188": 8,
  "191": 9,
  "192": 9,
  "193": 9,
  "200": 10,
  "201": 10,
  "202": 10,
  "203": 10,
  "204": 10,
  "211": 11,
  "212": 11,
  "213": 11,
  "214": 11,
  "221": 12,
  "222": 12,
  "223": 18,
  "224": 12,
  "225": 17,
  "227": 20,
  "231": 13,
  "232": 25,
  "235": 13,
  "236": 13,
  "241": 14,
  "242": 14,
  "251": 15,
  "261": 16,
  "271": 3,
  "273": 3,
  "274": 3,
  "346": 38,
  "347": 38,
};

export const GAME_MODES = {
  "0": {
    id: 0,
    name: "unknown",
    balanced: true,
  },
  "1": {
    id: 1,
    name: "all_pick",
    balanced: true,
  },
  "2": {
    id: 2,
    name: "captains_mode",
    balanced: true,
  },
  "3": {
    id: 3,
    name: "random_draft",
    balanced: true,
  },
  "4": {
    id: 4,
    name: "single_draft",
    balanced: true,
  },
  "5": {
    id: 5,
    name: "all_random",
    balanced: true,
  },
  "6": {
    id: 6,
    name: "intro",
  },
  "7": {
    id: 7,
    name: "diretide",
  },
  "8": {
    id: 8,
    name: "reverse_captains_mode",
  },
  "9": {
    id: 9,
    name: "greeviling",
  },
  "10": {
    id: 10,
    name: "tutorial",
  },
  "11": {
    id: 11,
    name: "mid_only",
  },
  "12": {
    id: 12,
    name: "least_played",
    balanced: true,
  },
  "13": {
    id: 13,
    name: "limited_heroes",
  },
  "14": {
    id: 14,
    name: "compendium_matchmaking",
  },
  "15": {
    id: 15,
    name: "custom",
  },
  "16": {
    id: 16,
    name: "captains_draft",
    balanced: true,
  },
  "17": {
    id: 17,
    name: "balanced_draft",
    balanced: true,
  },
  "18": {
    id: 18,
    name: "ability_draft",
  },
  "19": {
    id: 19,
    name: "event",
  },
  "20": {
    id: 20,
    name: "all_random_death_match",
  },
  "21": {
    id: 21,
    name: "1v1_mid",
  },
  "22": {
    id: 22,
    name: "all_draft",
    balanced: true,
  },
  "23": {
    id: 23,
    name: "turbo",
  },
  "24": {
    id: 24,
    name: "mutation",
  },
};

export const ATTRIBUTE_LEVELS = {
  17: 2,
  18: 2,
  19: 4,
  20: 4,
  21: 6,
  22: 8,
  23: 10,
  24: 12,
  25: 12,
  26: 14,
  27: 14,
  28: 14,
  29: 14,
  30: 14,
};

export const PLAYER_COLORS = {
  "0": "#3375FF",
  "1": "#66FFBF",
  "2": "#BF00BF",
  "3": "#F3F00B",
  "4": "#FF6B00",
  "128": "#FE86C2",
  "129": "#A1B447",
  "130": "#65D9F7",
  "131": "#008321",
  "132": "#A46900",
};

export const XP_LEVEL = [
  { 1: 0 },
  { 2: 230 },
  { 3: 600 },
  { 4: 1080 },
  { 5: 1660 },
  { 6: 2260 },
  { 7: 2980 },
  { 8: 3730 },
  { 9: 4620 },
  { 10: 5550 },
  { 11: 6520 },
  { 12: 7530 },
  { 13: 8580 },
  { 14: 9805 },
  { 15: 11055 },
  { 16: 12330 },
  { 17: 13630 },
  { 18: 14955 },
  { 19: 16455 },
  { 20: 18045 },
  { 21: 19645 },
  { 22: 21495 },
  { 23: 23595 },
  { 24: 25945 },
  { 25: 28545 },
  { 26: 32045 },
  { 27: 36545 },
  { 28: 42045 },
  { 29: 48545 },
  { 30: 56045 },
];
